### ISSUE TITLE
[BUG] oj-verify returns AC when CE occured

### ISSUE THREAD

**Issue by Tiphereth-A** [competitive-verifier/competitive-verifier#142]
log: <https://github.com/Tiphereth-A/CP-lib/actions/runs/6979939714>

verify (19) says that Failed to compile <https://github.com/Tiphereth-A/CP-lib/blob/70667ffe5a558d6fe4819eddf419a9737a7394fd/src/test_cpverifier/unit-test/geo2d/fermatp.cpp>, while it is treated as AC in summary.

I guess maybe oj-verify used some cached files that should have been cleared.

**Comment by kzrnm** [comment]
@Tiphereth-A Thanks for the report. I have fixed to detect compilation failure.
