### ISSUE TITLE
documentation_of に `..` が入っていると正しく紐づけされない

### ISSUE THREAD

**Issue by idat50me** [competitive-verifier/competitive-verifier#90]
`..` で親ディレクトリを示そうとしても、正しく解決されず markdown が表示されません。

### example
```
(root)
├── docs
│   └── aaa.md
├── xxx.cpp
└── bbb.md
```

- `aaa.md` で `documentation_of; ../xxx.cpp` -> 失敗
- `aaa.md` で `documentation_of: //xxx.cpp` -> 成功
- `bbb.md` で `documentation_of: xxx.cpp` -> 成功
- `bbb.md` で `documentation_of: ./xxx.cpp` -> 成功
- `bbb.md` で `documentation_of: docs/../xxx.cpp` ->失敗

**Comment by kzrnm** [comment]
相対パスの解決の順序が問題でした

**Comment by idat50me** [comment]
ありがとうございます、正常に動きました！
