### ISSUE TITLE
LIBRARY_PARTIAL_AC の絵文字を変える?

### ISSUE THREAD

**Issue by kzrnm** [competitive-verifier/competitive-verifier#92]
https://github.com/competitive-verifier/competitive-verifier/blob/bc30581761d4ae94f79f1daf8e9647dc2a7a67f0/src/competitive_verifier/models/dependency.py#L33

`competitive-verifier: IGNORE` でスキップしたときに依存先が ❓ なのは気持ち悪い気がする。

例: https://idat50me.github.io/cpp_lib/structure/2d_array.cpp

@idat50me よければ意見いただけませんか？

**Comment by idat50me** [comment]
少なくとも赤字はやめたほうがいい気がするので、❔ (grey_question) とかが一つの手ですかね
そもそも `IGNORE` がどのような用途で使われているか軽く調べた方がいいかもですが

**Comment by idat50me** [comment]
`IGNORE` の用途の例
- テストケースの不備で verify できない
	- https://idat50me.github.io/cpp_lib/test/aoj_0019.test.cpp
	- https://idat50me.github.io/cpp_lib/test/atc_nikkei2019-qual_d.test.cpp
- AC となる解答が複数ある（スペシャルジャッジが必要だが未対応）
	- https://idat50me.github.io/cpp_lib/test/aoj_GRL_4_B.test.cpp
- verify に時間がかかりすぎる
	- https://github.com/competitive-verifier/zzz_dr0gsk0l_library/blob/main/test/AOJ/GRL_5_E.test.cpp
- AtCoder や Codeforces などデフォルトで対応していないサイトの問題を使っている
	- https://emthrm.github.io/cp-library/test/math/bigint.07.test.cpp
	- https://emthrm.github.io/cp-library/test/math/bigint.08.test.cpp
	- https://matumoto1234.github.io/library/test/atcoder/abc/abc001/D.test.cpp

**Comment by idat50me** [comment]
思ったより見辛いかもです

![image](https://github.com/competitive-verifier/competitive-verifier/assets/59227194/5c343b2f-e7d6-4c48-8f1c-8996fd2c14cc)

**Comment by kzrnm** [comment]
ユースケースとしては「verify できない事情がある」が多そうなので :heavy_check_mark: の方が適しそうな気がしてきました。

それとは別に設定で変えられるようにしても良いでしょうね。

**Comment by idat50me** [comment]
`IGNORE` のものは無いものとして判定するのをデフォルトとして良いように思います。
（影響あるのは`AC_SKIP`だけでしょうか？）

https://github.com/competitive-verifier/competitive-verifier/blob/bc30581761d4ae94f79f1daf8e9647dc2a7a67f0/src/competitive_verifier/models/dependency.py#L72-L89

**Comment by kzrnm** [comment]
とりあえず分けといても困らなそうなので分けてます。

`_config.yml` で設定するようにしたのでユーザーが書き換え可能になる副産物もあり。
