### ISSUE TITLE
`DROPBOX_TOKEN` を自動更新する

### ISSUE THREAD

**Issue by idat50me** [competitive-verifier/competitive-verifier#95]
## 概要
dropboxのアクセストークンは長寿命のトークンが廃止されており、現在は4時間限定の短寿命なトークンしか生成できません。
そのため、トークンの寿命が切れる度に `DROPBOX_TOKEN` を手動で修正する必要があります。
参考：https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type

これを解決するためには、リフレッシュトークンを用いてverify実行時にアクセストークンを生成することが考えられます。
これは以下のコードで実現できます。
```python
import os
import dropbox

APP_KEY = os.environ.get("APP_KEY")
APP_SECRET = os.environ.get("APP_SECRET")
REFRESH_TOKEN = os.environ.get("REFRESH_TOKEN")

rdbx = dropbox.Dropbox(app_key=APP_KEY, app_secret=APP_SECRET, oauth2_refresh_token=REFRESH_TOKEN)
rdbx.users_get_current_account()
DROPBOX_TOKEN = rdbx.__dict__["_oauth2_access_token"]
```

oj.py を書き換えることで実現できますが、トークン取得部分は別ファイルに分けた方がいいかもと思っています。
@kzrnm 意見を聞かせていただきたいです。

https://github.com/competitive-verifier/competitive-verifier/blob/a2b66c700448b136e1f3bc1c49a4e8f343e03c91/src/competitive_verifier/oj.py#L91-L93

**Comment by kzrnm** [comment]
Dropbox 専用の処理となるとライブラリ外で対応したいかなあと思います。

GitHub Actions での使用を念頭に置くと verify 前に ↓ みたいなのを入れるというのが手段として良いかなと。

```yml
  - name: Set Dropbox token
    run: |
        DROPBOX_TOKEN=$( curl トークン取得URL | jq トークンのパス)
        echo "::add-mask::$DROPBOX_TOKEN"
        echo 'DROPBOX_TOKEN=$DROPBOX_TOKEN' >> $GITHUB_ENV
```

`::add-mask::` しないとログにトークンが漏れて良くないので要注意です。

https://docs.github.com/ja/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-a-log

**Comment by kzrnm** [comment]
https://github.com/idat50me/cpp_lib/pull/18

**Comment by idat50me** [comment]
無事動作しました。
